### ISSUE TITLE
Vector Addition: Equations master checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition-equations#1]
# Vector Addition: Equations master checklist

## Design
**Note** since this simulation is just the Equations screen published as a standalone, much of the checklist has been removed or is N/A
- [x] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional) - see #2
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder - see #4
  - [x] Sim primer draft - see #5 
 <s> - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive</s> - N/A, see https://github.com/phetsims/vector-addition/issues/255
  <s>- [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)</s> - N/A, see https://github.com/phetsims/vector-addition/issues/255
- [x] **Post-publication items**
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  <s>- [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)</s> - N/A, see https://github.com/phetsims/vector-addition/issues/255
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim) - see #5

## Implementation
- [x] **Repository created** (Date: 10/22/19)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 10/22/19)
- [x] **Sim is "feature complete"** (Date: 10/22/19)
- [x] **Code review completed** N/A
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots)) - see #2
  - [x] Verify credits - see #3
- [x] **Published** (Date: 11/5/19)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Dev testing started** N/A
- [x] **Dev testing completed** N/A
- [x] **First RC published** (Date: 10/23/19)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ) - N/A, no test matrix needed
- [x] **RC testing completed** (Date: 11/5/19)

**Comment by pixelzoom** [comment]
All tasks in the _Implementation_ and _QA_ sections have been completed.
